#spring.application.name=service-registry
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # We set these to false because this app IS the registry.
    # It doesn't need to register itself or fetch a list from itself.
    register-with-eureka: false
    fetch-registry: false