spring.application.name=apiGateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

server.port=8088
#userService
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path= /api/users/**

#taxpayerService
spring.cloud.gateway.routes[1].id=taxpayer-service
spring.cloud.gateway.routes[1].uri=lb://TAXPAYER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path= /api/taxpayers/**

#taxFilingService
spring.cloud.gateway.routes[2].id=tax-filing-service
spring.cloud.gateway.routes[2].uri=lb://tax-filing-service
spring.cloud.gateway.routes[2].predicates[0]=Path= /api/documents/**,/api/filings/**

#reportingService
spring.cloud.gateway.routes[3].id=REPORTING-SERVICE
spring.cloud.gateway.routes[3].uri=lb://REPORTING-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path= /api/reports/**

#paymentService
spring.cloud.gateway.routes[4].id=payment-service
spring.cloud.gateway.routes[4].uri=lb://payment-service
spring.cloud.gateway.routes[4].predicates[0]=Path= /api/payments/**

#notificationService
spring.cloud.gateway.routes[5].id=Notifications-SERVICE
spring.cloud.gateway.routes[5].uri=lb://Notifications-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path= /api/notifications/**

#complianceService
spring.cloud.gateway.routes[6].id=compliance-service
spring.cloud.gateway.routes[6].uri=lb://compliance-service
spring.cloud.gateway.routes[6].predicates[0]=Path= /api/compliance/**

#authenticationService
spring.cloud.gateway.routes[7].id=Authentication-Service
spring.cloud.gateway.routes[7].uri=lb://Authentication-Service
spring.cloud.gateway.routes[7].predicates[0]=Path= /api/auth/**

#auditService
spring.cloud.gateway.routes[8].id=AUDIT-SERVICE
spring.cloud.gateway.routes[8].uri=lb://AUDIT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/audit/**

#auditLogService
spring.cloud.gateway.routes[9].id=AUDITLOG-SERVICE
spring.cloud.gateway.routes[9].uri=lb://AUDITLOG-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path= /api/audit-logs/**



