spring.application.name=Authentication-Service
# Port where this service runs
server.port=8089

# Eureka Client Configuration
spring.config.import=optional:configserver:http://localhost:8888
internal.auth.header-name=X-Internal-Service-Key
internal.auth.secret-value=YourSuperSecretKey123