spring.application.name=reportingService
server.port=8082

# Database Configuration (Assuming it connects to the same local DB for now)
spring.datasource.url=jdbc:mysql://localhost:3306/taxease
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Disable Eureka for standalone Postman testing
eureka.client.enabled=false
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
