# ==========================================
# 1. SERVER & EUREKA CLIENT SETTINGS
# ==========================================
# Run on a different port than Eureka!
server.port=8087

# The name that will show up on the Eureka Dashboard
spring.application.name=REPORTING-SERVICE

# Point this service to your running Eureka Server
spring.config.import=optional:configserver:http://localhost:8888

# ==========================================
# 2. DATABASE CONFIGURATION
# ==========================================
# (Make sure to update the database name, username, and password to match your local MySQL setup)
spring.datasource.url=jdbc:mysql://localhost:3306/report_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

internal.auth.header-name=X-Internal-Service-Key
internal.auth.secret-value=YourSuperSecretKey123
